name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  run_tests_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checking out the repo
    - name: Run tests
      run: |
        /bin/bash test/test.sh
        exit $?
